sudo: required  
services:  
  - docker
install:  
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

script:  
  - docker build -f elasticsearch/Dockerfile -t $DOCKER_IMAGE_NAME:latest .
  - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:3.0.$TRAVIS_BUILD_NUMBER-alpha
  - docker push $DOCKER_IMAGE_NAME

env:  
  - DOCKER_IMAGE_NAME=ciandtsoftware/witix-elasticsearch
