sudo: required  
services:  
  - docker
install:  
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS

script:  
  - docker build -f elasticsearch/Dockerfile -t ciandtsoftware/witix-elasticsearch:latest .
  - docker tag ciandtsoftware/witix-elasticsearch:latest ciandtsoftware/witix-elasticsearch:3.0.$TRAVIS_BUILD_NUMBER-alpha
  - docker push ciandtsoftware/witix-elasticsearch

env:  
  - DOCKER_IMAGE_NAME=ciandtsoftware/witix-elasticsearch
