version: '2'
services:
    witix-nagios:
       build: Docker-Nagios
       networks:
         - witix    
       ports:
         - "8081:80"
    witix-elasticsearch:
        build: elasticsearch/
        ports:
            - "9300:9300"
        # uncomment this section to have elasticsearch data persisted to a volume
        #volumes:
        #   - ./elasticsearch/data:/usr/share/elasticsearch/data
        networks:
            - witix
    witix-kibana:
        build: kibana/
        depends_on: 
            - witix-elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://witix-elasticsearch:9200    
        networks:
            - witix
    witix-elastalert:
        build: elastalert/
        depends_on: 
            - witix-elasticsearch
        volumes:
            - ./elastalert/conf/config.yaml:/opt/elastalert/config.yaml
            - ./elastalert/conf/rules/:/opt/elastalert/rules                    
        networks:
            - witix
    witix-nginx:
        build: nginx/
        depends_on: 
            - witix-elasticsearch     
        ports:
            - "5601:5601"
            - "9200:9200"                       
        networks:
            - witix
networks:
    witix:
        ipam:
            config:
                - subnet: 10.2.2.0/24
